# Generated by Django 2.1.7 on 2019-05-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='shortcut_path',
        ),
        migrations.RemoveField(
            model_name='package',
            name='url',
        ),
        migrations.AddField(
            model_name='service',
            name='shortcut_path',
            field=models.TextField(default='/', verbose_name='Путь к ярлыку'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='url',
            field=models.SlugField(default='/', unique=True, verbose_name='URI ресурса'),
            preserve_default=False,
        ),
    ]
