# Generated by Django 2.2 on 2019-05-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_service',
            field=models.BooleanField(default=True, verbose_name='Услуга/Служебный'),
        ),
        migrations.AlterField(
            model_name='service',
            name='url',
            field=models.URLField(unique=True, verbose_name='URI ресурса'),
        ),
    ]
