# Generated by Django 2.1.7 on 2019-06-13 02:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190512_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Телефонный номер должен быть иметь следующий формат: '+999999999'. Максимальное количество цифр 15.", regex='^\\+?1?\\d{6,15}$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='service',
            name='shortcut_path',
            field=models.FileField(upload_to='media/', verbose_name='Путь к ярлыку'),
        ),
    ]
