# Generated by Django 2.2 on 2019-04-30 08:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20190430_0959'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerInfo',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='CoreProtocol',
            new_name='Protocol',
        ),
    ]
