# Generated by Django 2.1.7 on 2019-06-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190613_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='shortcut_path',
            field=models.ImageField(upload_to='', verbose_name='Путь к ярлыку'),
        ),
    ]
