# Generated by Django 2.2.3 on 2019-07-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190613_2140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Protocol',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='description',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='description',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='url',
            new_name='url_path',
        ),
        migrations.RemoveField(
            model_name='package',
            name='description',
        ),
        migrations.AlterField(
            model_name='service',
            name='is_service',
            field=models.BooleanField(default=True, verbose_name='Служебный'),
        ),
    ]
