# Generated by Django 2.2 on 2019-05-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190430_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='url',
        ),
        migrations.AddField(
            model_name='package',
            name='shortcut_path',
            field=models.TextField(default='', verbose_name='Путь к ярлыку'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='url',
            field=models.SlugField(default=' ', unique=True, verbose_name='URI ресурса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='protocol',
            name='user',
            field=models.CharField(default='Django admin', max_length=200),
        ),
    ]
